### ISSUE TITLE
Emphasise differences between this and the built-in calculator?

### ISSUE THREAD

**Issue by friday** [luasenvy/ulauncher-expr#1]
Ulauncher [has a calc-mode](https://github.com/Ulauncher/Ulauncher/blob/f18e1a748144f9b625b1ae182039465b1990ecee/ulauncher/search/calc/CalcMode.py), and most of your examples work with it (without the `expr`-keyword). It seems like yours can do things like concatenation and arbitrary eval statements, which the built-in calculator can't. Maybe you could emphasise this in the documentation to avoid confusion?

**Comment by luasenvy** [comment]
Of course.

until I saw this issue, I did not know that ulauncher had a built-in calculator.

Maybe ulauncher was so easy to use that I could not think of it.

Thank you for your good feedback. :)
